import type { Program } from './types'

/** Дэвид Лейд — DUP: два цикла push/pull/legs в неделю */
export const davidLaid: Program = {
  id: 'david-laid',
  author: 'Дэвид Лейд',
  title: 'DUP — Push / Pull / Legs ×2',
  subtitle: 'Каждое базовое движение дважды в неделю: тяжёлый день и объёмный',
  daysPerWeek: 6,
  split: '6 дней: push · pull · legs (тяжёлые) → push · pull · legs (объёмные)',
  level: 'продвинутый',
  goal: 'Сила и гипертрофия одновременно',
  spineSafe: false,
  source: 'Публичный DUP-план David Laid и его разборы',
  notes: [
    'Тяжёлые дни — 5×5 в базе, отдых 3 мин, прогрессия по весу.',
    'Объёмные дни — 10–15 повторов, отдых 60–90 сек, работа на пампинг.',
    'Прогрессия: +2.5 кг в базе, когда все 5 подходов закрыты чисто.',
    'Объём высокий — 6 дней подряд без разгрузочной недели не тянуть.',
  ],
  days: [
    {
      id: 'dl-d1',
      title: 'День 1 — Push (тяжёлый)',
      primaryType: 'chest',
      secondaryType: 'shoulders',
      exercises: [
        { exerciseId: 'bench-press', name: 'Жим лежа', muscleGroups: ['chest'], sets: 5, reps: 5 },
        { exerciseId: 'overhead-press', name: 'Жим стоя', muscleGroups: ['shoulders'], sets: 4, reps: 8 },
        { exerciseId: 'incline-dumbbell-press', name: 'Жим гантелей наклонный',
          muscleGroups: ['chest', 'shoulders'], sets: 3, reps: 10 },
        { exerciseId: 'lateral-raise', name: 'Махи в стороны',
          muscleGroups: ['shoulders'], sets: 4, reps: 12 },
        { exerciseId: 'tricep-pushdown', name: 'Разгибания на трицепс',
          muscleGroups: ['arms'], sets: 3, reps: 12 },
        { exerciseId: 'overhead-tricep', name: 'Французский жим', muscleGroups: ['arms'], sets: 3, reps: 12 },
      ],
    },
    {
      id: 'dl-d2',
      title: 'День 2 — Pull (тяжёлый)',
      primaryType: 'back',
      secondaryType: 'arms',
      exercises: [
        { exerciseId: 'deadlift', name: 'Становая тяга', muscleGroups: ['back', 'legs'], sets: 5, reps: 5 },
        { exerciseId: 'barbell-row', name: 'Тяга штанги в наклоне', muscleGroups: ['back'], sets: 4, reps: 8 },
        { exerciseId: 'pull-ups', name: 'Подтягивания', muscleGroups: ['back', 'arms'], sets: 4, reps: 8 },
        { exerciseId: 'cable-row', name: 'Тяга нижнего блока', muscleGroups: ['back'], sets: 3, reps: 12 },
        { exerciseId: 'barbell-curl', name: 'Сгибания со штангой', muscleGroups: ['arms'], sets: 4, reps: 10 },
        { exerciseId: 'face-pull', name: 'Фейс-пул', muscleGroups: ['shoulders', 'back'], sets: 3, reps: 15 },
      ],
    },
    {
      id: 'dl-d3',
      title: 'День 3 — Legs (тяжёлый)',
      primaryType: 'legs',
      exercises: [
        { exerciseId: 'squat', name: 'Приседания', muscleGroups: ['legs'], sets: 5, reps: 5 },
        { exerciseId: 'romanian-deadlift', name: 'Румынская тяга',
          muscleGroups: ['legs', 'back'], sets: 4, reps: 8 },
        { exerciseId: 'leg-press', name: 'Жим ногами', muscleGroups: ['legs'], sets: 3, reps: 12 },
        { exerciseId: 'leg-curl', name: 'Сгибания ног', muscleGroups: ['legs'], sets: 3, reps: 12 },
        { exerciseId: 'calf-raise', name: 'Подъемы на носки', muscleGroups: ['legs'], sets: 4, reps: 15 },
      ],
    },
    {
      id: 'dl-d4',
      title: 'День 4 — Push (объёмный)',
      primaryType: 'chest',
      secondaryType: 'shoulders',
      exercises: [
        { exerciseId: 'incline-bench-press', name: 'Жим лежа наклонный',
          muscleGroups: ['chest', 'shoulders'], sets: 4, reps: 10 },
        { exerciseId: 'chest-press-machine', name: 'Жим в тренажере',
          muscleGroups: ['chest'], sets: 3, reps: 12 },
        { exerciseId: 'cable-crossover', name: 'Кроссовер', muscleGroups: ['chest'], sets: 3, reps: 15 },
        { exerciseId: 'cable-lateral-raise', name: 'Махи в стороны на блоке',
          muscleGroups: ['shoulders'], sets: 4, reps: 15 },
        { exerciseId: 'dips', name: 'Брусья', muscleGroups: ['chest', 'arms'], sets: 3, reps: 12 },
        { exerciseId: 'tricep-pushdown', name: 'Разгибания на трицепс',
          muscleGroups: ['arms'], sets: 3, reps: 15 },
      ],
    },
    {
      id: 'dl-d5',
      title: 'День 5 — Pull (объёмный)',
      primaryType: 'back',
      secondaryType: 'arms',
      exercises: [
        { exerciseId: 'lat-pulldown', name: 'Тяга верхнего блока', muscleGroups: ['back'], sets: 4, reps: 12 },
        { exerciseId: 'chest-supported-row', name: 'Тяга с упором в скамью',
          muscleGroups: ['back'], sets: 4, reps: 12 },
        { exerciseId: 't-bar-row', name: 'Тяга Т-грифа', muscleGroups: ['back'], sets: 3, reps: 12 },
        { exerciseId: 'rear-delt-fly', name: 'Разводка на заднюю дельту',
          muscleGroups: ['shoulders'], sets: 3, reps: 15 },
        { exerciseId: 'hammer-curl', name: 'Молотки', muscleGroups: ['arms'], sets: 3, reps: 12 },
        { exerciseId: 'preacher-curl', name: 'Сгибания на скамье Скотта',
          muscleGroups: ['arms'], sets: 3, reps: 12 },
      ],
    },
    {
      id: 'dl-d6',
      title: 'День 6 — Legs (объёмный)',
      primaryType: 'legs',
      exercises: [
        { exerciseId: 'hack-squat', name: 'Гакк-приседания', muscleGroups: ['legs'], sets: 4, reps: 12 },
        { exerciseId: 'bulgarian-split-squat', name: 'Болгарские выпады',
          muscleGroups: ['legs'], sets: 3, reps: 10 },
        { exerciseId: 'leg-extension', name: 'Разгибания ног', muscleGroups: ['legs'], sets: 4, reps: 15 },
        { exerciseId: 'leg-curl', name: 'Сгибания ног', muscleGroups: ['legs'], sets: 4, reps: 15 },
        { exerciseId: 'hip-thrust', name: 'Ягодичный мост', muscleGroups: ['legs'], sets: 3, reps: 12 },
        { exerciseId: 'calf-raise', name: 'Подъемы на носки', muscleGroups: ['legs'], sets: 4, reps: 20 },
      ],
    },
  ],
}
