import type { Program } from './types'

/** Личный гибрид: объём Холланда + логика DUP, без осевой нагрузки на позвоночник */
export const hybrid: Program = {
  id: 'hybrid-spine-safe',
  author: 'Мой гибрид',
  title: 'Гибрид: верх Холланда + логика DUP, спина защищена',
  subtitle: 'Без приседа, становой, жима стоя и бега — вертикальная нагрузка на позвоночник снята',
  daysPerWeek: 5,
  split: '5 дней: push · pull · ноги · корсет · спина-акцент, шестой день растяжка',
  level: 'средний',
  goal: 'Сухая масса верха, стабильный корсет, отсутствие обострений',
  spineSafe: true,
  notes: [
    'Осевые движения исключены: вместо приседа — жим ногами, вместо жима стоя — жим сидя с упором.',
    'Тяги — только с опорой корпуса (блок, упор в скамью), без наклона со штангой.',
    'Рабочий диапазон 6–8 повторений: закрыть 6 во всех подходах, довести до 8, затем +вес.',
    'Кардио — эллипс или ходьба на дорожке в наклоне, без бега и прыжков.',
    'Гиперэкстензия — без веса и без переразгибания, амплитуда до нейтрали.',
    'Любая боль по ходу нерва — движение убирается, а не «дотерпливается».',
    'Пятый день ставится, если неделя без пропусков; при пропуске уходит первым.',
    'Шестой день — растяжка и асаны, седьмой — отдых.',
  ],
  days: [
    {
      id: 'hy-d1',
      title: 'День 1 — Push (всё сидя или лёжа)',
      primaryType: 'chest',
      secondaryType: 'shoulders',
      exercises: [
        { exerciseId: 'bench-press', name: 'Жим лежа', muscleGroups: ['chest'], sets: 4, reps: 8 },
        { exerciseId: 'incline-dumbbell-press', name: 'Жим гантелей наклонный',
          muscleGroups: ['chest', 'shoulders'], sets: 3, reps: 8 },
        { exerciseId: 'dumbbell-shoulder-press', name: 'Жим гантелей сидя',
          muscleGroups: ['shoulders'], sets: 4, reps: 8, note: 'Спина плотно в спинку скамьи' },
        { exerciseId: 'cable-crossover', name: 'Кроссовер', muscleGroups: ['chest'], sets: 3, reps: 8 },
        { exerciseId: 'cable-lateral-raise', name: 'Махи в стороны на блоке',
          muscleGroups: ['shoulders'], sets: 4, reps: 8,
          note: 'Средние дельты — единственная точка нагрузки на группу, 3 подхода было мало' },
        { exerciseId: 'tricep-pushdown', name: 'Разгибания на трицепс',
          muscleGroups: ['arms'], sets: 3, reps: 8 },
      ],
    },
    {
      id: 'hy-d2',
      title: 'День 2 — Pull (с опорой корпуса)',
      primaryType: 'back',
      secondaryType: 'arms',
      exercises: [
        { exerciseId: 'lat-pulldown', name: 'Тяга верхнего блока', muscleGroups: ['back'], sets: 4, reps: 8 },
        { exerciseId: 'chest-supported-row', name: 'Тяга с упором в скамью',
          muscleGroups: ['back'], sets: 4, reps: 8 },
        { exerciseId: 'cable-row', name: 'Тяга нижнего блока', muscleGroups: ['back'], sets: 3, reps: 8,
          note: 'Корпус вертикально, без раскачки' },
        { exerciseId: 'face-pull', name: 'Фейс-пул', muscleGroups: ['shoulders', 'back'], sets: 3, reps: 8 },
        { exerciseId: 'preacher-curl', name: 'Сгибания на скамье Скотта',
          muscleGroups: ['arms'], sets: 3, reps: 8 },
        { exerciseId: 'hammer-curl', name: 'Молотки', muscleGroups: ['arms'], sets: 3, reps: 8,
          note: 'Сидя' },
      ],
    },
    {
      id: 'hy-d3',
      title: 'День 3 — Ноги без осевой нагрузки',
      primaryType: 'legs',
      exercises: [
        { exerciseId: 'leg-press', name: 'Жим ногами', muscleGroups: ['legs'], sets: 4, reps: 8,
          note: 'Поясница прижата, без отрыва таза' },
        { exerciseId: 'leg-extension', name: 'Разгибания ног', muscleGroups: ['legs'], sets: 3, reps: 8 },
        { exerciseId: 'leg-curl', name: 'Сгибания ног', muscleGroups: ['legs'], sets: 4, reps: 8 },
        { exerciseId: 'hip-thrust', name: 'Ягодичный мост', muscleGroups: ['legs'], sets: 3, reps: 8 },
        { exerciseId: 'step-up', name: 'Зашагивания на платформу', muscleGroups: ['legs'], sets: 3, reps: 8,
          note: 'Гантели в руках, вес умеренный' },
        { exerciseId: 'calf-raise', name: 'Подъемы на носки', muscleGroups: ['legs'], sets: 4, reps: 8,
          note: 'Сидя, не со штангой на плечах' },
      ],
    },
    {
      id: 'hy-d4',
      title: 'День 4 — Корсет и кондиция',
      primaryType: 'core',
      secondaryType: 'cardio',
      exercises: [
        { exerciseId: 'pallof-press', name: 'Жим Паллофа', muscleGroups: ['core'], sets: 3, reps: 12,
          note: 'На каждую сторону' },
        { exerciseId: 'plank', name: 'Планка', muscleGroups: ['core'], sets: 3, reps: 45,
          note: 'Повторы = секунды' },
        { exerciseId: 'ab-wheel', name: 'Ролик для пресса', muscleGroups: ['core'], sets: 3, reps: 10,
          note: 'Короткая амплитуда, поясница не провисает' },
        { exerciseId: 'hyperextension', name: 'Гиперэкстензия',
          muscleGroups: ['back', 'core'], sets: 3, reps: 15, note: 'Без веса, до нейтрали' },
        { exerciseId: 'push-ups', name: 'Отжимания', muscleGroups: ['chest', 'arms'], sets: 3, reps: 20 },
        { exerciseId: 'elliptical', name: 'Эллипс', muscleGroups: ['cardio'], sets: 1, reps: 1200,
          note: 'Повторы = секунды, ровный пульс; замена — быстрая ходьба на дорожке в наклоне' },
      ],
    },
    {
      id: 'hy-d5',
      title: 'День 5 — Спина-акцент (объём, лёгкие веса)',
      primaryType: 'back',
      secondaryType: 'rear-delts',
      exercises: [
        { exerciseId: 'cable-row', name: 'Тяга нижнего блока', muscleGroups: ['back'],
          sets: 4, reps: 8, note: 'Корпус вертикально, вес на 20% ниже дня 2' },
        { exerciseId: 'lat-pulldown', name: 'Тяга верхнего блока', muscleGroups: ['back'],
          sets: 3, reps: 8, note: 'Широкий хват, пауза в нижней точке' },
        { exerciseId: 'face-pull', name: 'Фейс-пул', muscleGroups: ['rear-delts'],
          sets: 4, reps: 8, note: 'Задние дельты и внешняя ротация' },
        { exerciseId: 'трапеция-шраги', name: 'Трапеция шраги', muscleGroups: ['traps'],
          sets: 3, reps: 8, note: 'Гантели по бокам, без штанги стоя' },
        { exerciseId: 'hyperextension', name: 'Гиперэкстензия', muscleGroups: ['lower-back'],
          sets: 3, reps: 15, note: 'Без веса, до нейтрали' },
        { exerciseId: 'pallof-press', name: 'Жим Паллофа', muscleGroups: ['core'],
          sets: 3, reps: 12, note: 'На каждую сторону' },
      ],
    },
    {
      id: 'hy-d6',
      title: 'День 6 — Растяжка и асаны',
      primaryType: 'stretching',
      exercises: [
        { exerciseId: 'plank', name: 'Планка', muscleGroups: ['core'], sets: 3, reps: 45,
          note: 'Повторы = секунды, как разогрев корсета перед растяжкой' },
      ],
      note: 'Основной состав — 6–8 асан по 45–60 секунд, см. docs/asanas.md',
    },
  ],
}
