import type { Program } from './types'

/** Личный гибрид: объём Холланда + логика DUP, без осевой нагрузки на позвоночник */
export const hybrid: Program = {
  id: 'hybrid-spine-safe',
  author: 'Мой гибрид',
  title: 'Гибрид: верх Холланда + логика DUP, спина защищена',
  subtitle: 'Без приседа, становой, жима стоя и бега — вертикальная нагрузка на позвоночник снята',
  daysPerWeek: 4,
  split: '4 дня: push · pull · ноги (тренажёры) · корсет и кондиция',
  level: 'средний',
  goal: 'Сухая масса верха, стабильный корсет, отсутствие обострений',
  spineSafe: true,
  notes: [
    'Осевые движения исключены: вместо приседа — жим ногами, вместо жима стоя — жим сидя с упором.',
    'Тяги — только с опорой корпуса (блок, упор в скамью), без наклона со штангой.',
    'Прогрессия сначала по повторам в верхней границе диапазона, затем +2.5 кг.',
    'Кардио — эллипс или ходьба на дорожке в наклоне, без бега и прыжков.',
    'Гиперэкстензия — без веса и без переразгибания, амплитуда до нейтрали.',
    'Любая боль по ходу нерва — движение убирается, а не «дотерпливается».',
  ],
  days: [
    {
      id: 'hy-d1',
      title: 'День 1 — Push (всё сидя или лёжа)',
      primaryType: 'chest',
      secondaryType: 'shoulders',
      exercises: [
        { exerciseId: 'bench-press', name: 'Жим лежа', muscleGroups: ['chest'], sets: 4, reps: 8 },
        { exerciseId: 'incline-dumbbell-press', name: 'Жим гантелей наклонный',
          muscleGroups: ['chest', 'shoulders'], sets: 3, reps: 10 },
        { exerciseId: 'dumbbell-shoulder-press', name: 'Жим гантелей сидя',
          muscleGroups: ['shoulders'], sets: 4, reps: 10, note: 'Спина плотно в спинку скамьи' },
        { exerciseId: 'cable-crossover', name: 'Кроссовер', muscleGroups: ['chest'], sets: 3, reps: 15 },
        { exerciseId: 'cable-lateral-raise', name: 'Махи в стороны на блоке',
          muscleGroups: ['shoulders'], sets: 3, reps: 15 },
        { exerciseId: 'tricep-pushdown', name: 'Разгибания на трицепс',
          muscleGroups: ['arms'], sets: 3, reps: 12 },
      ],
    },
    {
      id: 'hy-d2',
      title: 'День 2 — Pull (с опорой корпуса)',
      primaryType: 'back',
      secondaryType: 'arms',
      exercises: [
        { exerciseId: 'lat-pulldown', name: 'Тяга верхнего блока', muscleGroups: ['back'], sets: 4, reps: 10 },
        { exerciseId: 'chest-supported-row', name: 'Тяга с упором в скамью',
          muscleGroups: ['back'], sets: 4, reps: 10 },
        { exerciseId: 'cable-row', name: 'Тяга нижнего блока', muscleGroups: ['back'], sets: 3, reps: 12,
          note: 'Корпус вертикально, без раскачки' },
        { exerciseId: 'face-pull', name: 'Фейс-пул', muscleGroups: ['shoulders', 'back'], sets: 3, reps: 15 },
        { exerciseId: 'preacher-curl', name: 'Сгибания на скамье Скотта',
          muscleGroups: ['arms'], sets: 3, reps: 12 },
        { exerciseId: 'hammer-curl', name: 'Молотки', muscleGroups: ['arms'], sets: 3, reps: 12,
          note: 'Сидя' },
      ],
    },
    {
      id: 'hy-d3',
      title: 'День 3 — Ноги без осевой нагрузки',
      primaryType: 'legs',
      exercises: [
        { exerciseId: 'leg-press', name: 'Жим ногами', muscleGroups: ['legs'], sets: 4, reps: 12,
          note: 'Поясница прижата, без отрыва таза' },
        { exerciseId: 'leg-extension', name: 'Разгибания ног', muscleGroups: ['legs'], sets: 3, reps: 15 },
        { exerciseId: 'leg-curl', name: 'Сгибания ног', muscleGroups: ['legs'], sets: 4, reps: 12 },
        { exerciseId: 'hip-thrust', name: 'Ягодичный мост', muscleGroups: ['legs'], sets: 3, reps: 12 },
        { exerciseId: 'step-up', name: 'Зашагивания на платформу', muscleGroups: ['legs'], sets: 3, reps: 10,
          note: 'Гантели в руках, вес умеренный' },
        { exerciseId: 'calf-raise', name: 'Подъемы на носки', muscleGroups: ['legs'], sets: 4, reps: 15,
          note: 'Сидя, не со штангой на плечах' },
      ],
    },
    {
      id: 'hy-d4',
      title: 'День 4 — Корсет и кондиция',
      primaryType: 'core',
      secondaryType: 'cardio',
      exercises: [
        { exerciseId: 'pallof-press', name: 'Жим Паллофа', muscleGroups: ['core'], sets: 3, reps: 12,
          note: 'На каждую сторону' },
        { exerciseId: 'plank', name: 'Планка', muscleGroups: ['core'], sets: 3, reps: 45,
          note: 'Повторы = секунды' },
        { exerciseId: 'ab-wheel', name: 'Ролик для пресса', muscleGroups: ['core'], sets: 3, reps: 10,
          note: 'Короткая амплитуда, поясница не провисает' },
        { exerciseId: 'hyperextension', name: 'Гиперэкстензия',
          muscleGroups: ['back', 'core'], sets: 3, reps: 15, note: 'Без веса, до нейтрали' },
        { exerciseId: 'push-ups', name: 'Отжимания', muscleGroups: ['chest', 'arms'], sets: 3, reps: 20 },
        { exerciseId: 'elliptical', name: 'Эллипс', muscleGroups: ['cardio'], sets: 1, reps: 1200,
          note: 'Повторы = секунды, ровный пульс; замена — быстрая ходьба на дорожке в наклоне' },
      ],
    },
  ],
}
