import type { Program } from './types'

/** Том Холланд — тренер Дафф Гейвер, подготовка к «Человеку-пауку» */
export const tomHolland: Program = {
  id: 'tom-holland',
  author: 'Том Холланд',
  title: 'Spider-Man: база + калистеника',
  subtitle: 'Классический бодибилдинг-сплит плюс день гимнастики и кондиции',
  daysPerWeek: 5,
  split: '5 дней: грудь · спина · плечи/пресс · ноги · калистеника',
  level: 'средний',
  goal: 'Сухая масса, плотный верх, выносливость',
  spineSafe: false,
  source: 'Публичные интервью Даффа Гейвера и разборы подготовки к съёмкам',
  notes: [
    'Основа — базовые движения со штангой и гантелями, без экзотики.',
    'Много собственного веса: подтягивания, брусья, отжимания каждую неделю.',
    'Кардио низкой интенсивности 3–4 раза в неделю по 20–30 минут.',
    'Отдых между подходами 60–90 сек, в день калистеники — 30–45 сек.',
  ],
  days: [
    {
      id: 'th-d1',
      title: 'День 1 — Грудь и трицепс',
      primaryType: 'chest',
      secondaryType: 'arms',
      exercises: [
        { exerciseId: 'bench-press', name: 'Жим лежа', muscleGroups: ['chest'], sets: 4, reps: 8 },
        { exerciseId: 'incline-dumbbell-press', name: 'Жим гантелей наклонный',
          muscleGroups: ['chest', 'shoulders'], sets: 4, reps: 10 },
        { exerciseId: 'dips', name: 'Брусья', muscleGroups: ['chest', 'arms'], sets: 3, reps: 12,
          note: 'До отказа, при легкости — с весом' },
        { exerciseId: 'cable-crossover', name: 'Кроссовер', muscleGroups: ['chest'], sets: 3, reps: 12 },
        { exerciseId: 'close-grip-bench', name: 'Жим узким хватом',
          muscleGroups: ['arms', 'chest'], sets: 3, reps: 10 },
        { exerciseId: 'tricep-pushdown', name: 'Разгибания на трицепс',
          muscleGroups: ['arms'], sets: 3, reps: 12 },
      ],
    },
    {
      id: 'th-d2',
      title: 'День 2 — Спина и бицепс',
      primaryType: 'back',
      secondaryType: 'arms',
      exercises: [
        { exerciseId: 'pull-ups', name: 'Подтягивания', muscleGroups: ['back', 'arms'],
          sets: 5, reps: 10, note: 'Цель — 50 повторов суммой' },
        { exerciseId: 'barbell-row', name: 'Тяга штанги в наклоне',
          muscleGroups: ['back'], sets: 4, reps: 8 },
        { exerciseId: 'lat-pulldown', name: 'Тяга верхнего блока',
          muscleGroups: ['back'], sets: 3, reps: 12 },
        { exerciseId: 'cable-row', name: 'Тяга нижнего блока', muscleGroups: ['back'], sets: 3, reps: 12 },
        { exerciseId: 'barbell-curl', name: 'Сгибания со штангой', muscleGroups: ['arms'], sets: 4, reps: 10 },
        { exerciseId: 'hammer-curl', name: 'Молотки', muscleGroups: ['arms'], sets: 3, reps: 12 },
      ],
    },
    {
      id: 'th-d3',
      title: 'День 3 — Плечи и пресс',
      primaryType: 'shoulders',
      secondaryType: 'core',
      exercises: [
        { exerciseId: 'dumbbell-shoulder-press', name: 'Жим гантелей сидя',
          muscleGroups: ['shoulders'], sets: 4, reps: 10 },
        { exerciseId: 'lateral-raise', name: 'Махи в стороны',
          muscleGroups: ['shoulders'], sets: 4, reps: 12 },
        { exerciseId: 'rear-delt-fly', name: 'Разводка на заднюю дельту',
          muscleGroups: ['shoulders'], sets: 3, reps: 15 },
        { exerciseId: 'shrugs', name: 'Шраги', muscleGroups: ['shoulders'], sets: 3, reps: 12 },
        { exerciseId: 'leg-raise', name: 'Подъемы ног', muscleGroups: ['core'], sets: 3, reps: 15,
          note: 'В висе на перекладине' },
        { exerciseId: 'plank', name: 'Планка', muscleGroups: ['core'], sets: 3, reps: 60,
          note: 'Повторы = секунды' },
      ],
    },
    {
      id: 'th-d4',
      title: 'День 4 — Ноги',
      primaryType: 'legs',
      exercises: [
        { exerciseId: 'squat', name: 'Приседания', muscleGroups: ['legs'], sets: 4, reps: 8 },
        { exerciseId: 'leg-press', name: 'Жим ногами', muscleGroups: ['legs'], sets: 3, reps: 12 },
        { exerciseId: 'lunges', name: 'Выпады', muscleGroups: ['legs'], sets: 3, reps: 12 },
        { exerciseId: 'leg-curl', name: 'Сгибания ног', muscleGroups: ['legs'], sets: 3, reps: 12 },
        { exerciseId: 'calf-raise', name: 'Подъемы на носки', muscleGroups: ['legs'], sets: 4, reps: 15 },
      ],
    },
    {
      id: 'th-d5',
      title: 'День 5 — Калистеника и кондиция',
      primaryType: 'core',
      secondaryType: 'cardio',
      exercises: [
        { exerciseId: 'push-ups', name: 'Отжимания', muscleGroups: ['chest', 'arms'], sets: 5, reps: 25 },
        { exerciseId: 'pull-ups', name: 'Подтягивания', muscleGroups: ['back', 'arms'], sets: 5, reps: 8 },
        { exerciseId: 'dips', name: 'Брусья', muscleGroups: ['chest', 'arms'], sets: 4, reps: 12 },
        { exerciseId: 'burpee', name: 'Бёрпи', muscleGroups: ['cardio', 'legs'], sets: 5, reps: 15 },
        { exerciseId: 'jump-rope', name: 'Скакалка', muscleGroups: ['cardio', 'legs'], sets: 3, reps: 180,
          note: 'Повторы = секунды' },
        { exerciseId: 'crunch', name: 'Скручивания', muscleGroups: ['core'], sets: 3, reps: 25 },
      ],
    },
  ],
}
